# This is the network config written by 'subiquity' -> typical file location /etc/netplan/00-installer-config.yaml
network:
  ethernets:
    ens33:
      dhcp4: false
      addresses:
        - 192.168.253.101/24
      routes:
        - to: default
          via: 192.168.253.2
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
  version: 2
# after the correct configuration do this command on the shell -> $ netplan apply
